### ISSUE TITLE
Error 2406

### ISSUE THREAD

**Issue by Bentrama** [tuya/tuya-homebridge#134]
Hello

im trying to setup home bridge but it doesn’t work.
I always get error 2406 : Skill Invalid.
My data center is set to : Central Europe 
I’m from Belgium and selected Belgium in the Tuya app 
My app is linked to the Tuya IOT platform 
Acces ID and access key are correct also 
Login and password on home bridge plugin are the same as the app

but it doesn’t work. Always return a 2406 error. What can I do ?

**Comment by Bentrama** [comment]
> The only thing you need to do is changing the endpoint:
> 
> ```
> //this.endpoint = (this.countryCode && this.countryCode == 86)? 'https://openapi.tuyacn.com' : 'https://openapi.tuyaus.com'
> this.endpoint = 'https://openapi.tuyaeu.com';
> ```

Where should I change it ?

**Comment by Bentrama** [comment]
![22114967-6416-4366-81E3-A8144815CFBB](https://user-images.githubusercontent.com/92755428/138250919-4535cbc2-ac24-46d7-86dc-3d5f4dea7d52.jpeg)

i tried what you asked but get this error now

**Comment by TheWojtek** [comment]
Most probably this one is a copy of https://github.com/tuya/tuya-homebridge/issues/131

**Comment by Tomaholk1** [comment]
https://github.com/tuya/tuya-homebridge/issues/144

**Comment by Hanh94** [comment]
Hi guys, Sorry for the late reply.
Recently our server is making cross-region adjustment of devices, so foreign cross-region cannot access each other. Tuya HB plugin has fixed this problem, and a new version will be released soon.

**Comment by Hanh94** [comment]
The issue has been fixed and released in version 1.5.0

**Comment by chrise86** [comment]
@Hanh94 since 1.5.0 I cannot login at all. I just get error 1106 all the time now.

**Comment by ryanlbates01** [comment]
@Hanh94 I too am now getting the 1106 error since updating to 1.5.0

**Comment by ryanlbates01** [comment]
@Hanh94 I have also tried rolling back to 1.4.2 and i am still getting the 1106 error

**Comment by jlucasnc** [comment]
Hello. I can't access too. I did the change on URL but same issue:

`TuyaOpenAPI response: {"code":1106,"msg":"permission deny","success":false,"t":1636072232018} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.`

What are the data centres options you are using? Thanks in advance.

**Comment by Hanh94** [comment]
Hi guys.
Sorry for the inconvenience, we have found the cause of the 1106 error, it's related to the account password validation, not related to v1.5.0. We will fix it ASAP.

**Comment by ryanlbates01** [comment]
@Hanh94 Do you have an ETA on a fix/resolution to the 1106 error?

**Comment by bluntiless** [comment]
Hi everyone, I was getting the same error yesterday and it was resolved. However it has come back again this morning:


TuyaOpenAPI response: {"code":1109,"msg":"param is illegal, please check it","success":false,"t":1636109496612} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:48:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at TuyaSHOpenAPI.request (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:144:7)
    at TuyaSHOpenAPI.getDevices (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:62:15)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!

**Comment by bluntiless** [comment]
TuyaOpenAPI response: {"code":2406,"msg":"skill id invalid","success":false,"t":1636116141984} path = /v1.0/iot-01/associated-users/actions/authorized-login
TypeError: Cannot destructure property 'access_token' of 'res.result' as it is undefined.
    at TuyaSHOpenAPI._refreshAccessTokenIfNeed (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:49:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at TuyaSHOpenAPI.request (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:145:7)
    at TuyaSHOpenAPI.getDevices (/usr/local/lib/node_modules/homebridge-tuya-platform/lib/tuyashopenapi.js:63:15)
    at TuyaPlatform.initTuyaSDK (/usr/local/lib/node_modules/homebridge-tuya-platform/index.js:90:19)
Attention⚠️ ⚠️ ⚠️ ! You get an error!
Failed to get device information. Please check if the config.json is correct.

**Comment by xrust83** [comment]
I have the same problem. On the website Tuya api already offer to include some kind of plan for $ 1200 or go to the Trial Edition plan for 1 month. If they want money this will be the last TuYa device I bought.

**Comment by JaredSartin** [comment]
> Hi guys. Sorry for the inconvenience, we have found the cause of the 1106 error, it's related to the account password validation, not related to v1.5.0. We will fix it ASAP.

Still being worked on?

**Comment by DJBenson** [comment]
> Keep in mind the password in plugin configuration must be the password from the mobile app and **not** the password from the iot.tuya.com

Really important point!!

**Comment by JaredSartin** [comment]
That’s what it was. Had to setup a password, was using the Google login.

**Comment by dehness** [comment]
Same issue for me...

**Comment by Ieuanoh** [comment]
For anyone having this issue - I was able to fix it by manually entering the config values into the Homebridge ui config json rather than using the input fields in the plugin. The main ones that seemed to be missing from when it was configured with the plugin ui were 'countryCode' and 'endpoint'. Take a look at the instructions on the readme to see what these values should be rather than relying on the plugin ui. Also the country code should be a number (e.g. 44 for United Kingdom) not the country code as stated in the plugin ui. This fixed the issue for me. Hope this helps! 

The plugin ui should be fixed to account for this or the docs should clarify this a little more.

**Comment by igorayres-falepaco** [comment]
Hello guys, i'm with this same erros...

Anyone can help?

TuyaOpenAPI response: {“code”:2406,“msg”:“skill id invalid”
Failed to get device information. Please check if the config.json is correct.

this is my config.js file:


{
    "bridge": {
        "name": "homebridge-tuya-platform",
        "username": "BE:B9:AC:79:6C:CA",
        "port": 8081,
        "pin": "034-85-687"
    },

    "description": "This is an Homebridge Plugin of Tuya.",

    "platforms": [
        {
            "platform": "TuyaPlatform",
            "name": "TuyaPlatform",
            "options":
              {
                "username": "some_email",
                "password": "some_pass",
                "accessId": "some_id",
                "accessKey": "some_key",
                "lang": "en",
                "endPoint":"https://openapi.tuyaus.com",
                "projectType": "2",
                "appSchema": "tuyaSmart",
                "countryCode": 44,
                "debug":true
              }
        }
    ]
}

I’m in Brazil, and already try few contry codes: 86, 55 but noone worked…

**Comment by igorayres-falepaco** [comment]
> For anyone having this issue - I was able to fix it by manually entering the config values into the Homebridge ui config json rather than using the input fields in the plugin. The main ones that seemed to be missing from when it was configured with the plugin ui were 'countryCode' and 'endpoint'. Take a look at the instructions on the readme to see what these values should be rather than relying on the plugin ui. Also the country code should be a number (e.g. 44 for United Kingdom) not the country code string (e.g. gb) as stated in the plugin ui. This fixed the issue for me. Hope this helps!
> 
> The plugin ui should be fixed to account for this or the docs should clarify this a little more.

Hello my friend,

Could you please share your config.js file?

**Comment by igorayres-falepaco** [comment]
Hello everyone, I DID IT!

First of all, only work on my new tuya accont, I have a 2 years tuya account, and I just can't make work, so if your Tuya account is 6 months or older, I recommend create a new one.

When I create a new cloud project on tuya platform, I'm select both servers: Eastern and Western (I'm in Brazil). 

On Devices - link tuya app account, I have to conect with my app account on both servers (Westean and Eastern), I have to make this procedure, twice (read the QR code)

![western](https://user-images.githubusercontent.com/65417490/153665156-09f91d99-e4de-4486-95e6-0f5a575d1fcd.png)


After this, I just return om my homebridge server, put my account information, and IT's WORKS!!

This is my config.js file:

![image](https://user-images.githubusercontent.com/65417490/153665305-920e6805-6431-4646-8613-9736088df79d.png)

**Comment by leo150** [comment]
I reported 1109 to tuya support and they answered:
> Hi dear, thank you for contacting Tuya. Your issue is being handled. Thank you for your patience.

You can reported the issue here https://service.console.tuya.com/ for faster "handling".

**Comment by Licencraft** [comment]
Year after - issue not close T_T
